name: DAST

on:
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for app to be healthy
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5000/ > /dev/null; then
              echo "App is up!" && exit 0
            fi
            echo "Waiting for app..."
            sleep 3
          done
          echo "App did not become healthy in time" && exit 1

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:5000/'
          fail_action: false

      - name: Tear down Docker Compose
        if: always()
        run: docker compose down
