# .github/workflows/sast.yml
#
# GitHub Actions workflow for Static Application Security Testing (SAST)
# and container image scanning.
#
# Steps:
#   1. Checkout code
#   2. Set up Python
#   3. Install Bandit
#   4. Run Bandit SAST scan
#   5. Build Docker image
#   6. Run Trivy vulnerability scan
#   7. Upload Trivy report
#
# Triggers on push, pull_request, and manual dispatch.

name: SAST Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit SAST scan
        run: |
          bandit -r app.py || true

      - name: Build Docker image for app
        run: |
          docker build -f Dockerfile -t myapp:latest .

      - name: Run Trivy vulnerability scan on app image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest
          format: 'table'
          exit-code: '0'
          output: 'trivy-report.txt'

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt
